[colors.primary]
background = "#1d1d20"
foreground = "#dcdcdc"

[colors.normal]
black = "#000000"
red = "#cd3131"
green = "#0dbc79"
yellow = "#e5e510"
blue = "#7b5cff"  #No blue. Set to purple for fastfetch. Old color 2472c8
magenta = "#bc3fbc"
cyan = "#11a8cd"
white = "#e5e5e5"

[colors.bright]
black = "#666666"
red = "#f14c4c"
green = "#23d18b"
yellow = "#f5f543"
blue = "#3b8eea"
magenta = "#d670d6"
cyan = "#29b8db"
white = "#e5e5e5"


